basePath: /api/v1
definitions:
  request.Reservation:
    properties:
      client_id:
        type: integer
      end_at:
        type: string
      number_of_guests:
        type: integer
      restaurant_id:
        type: integer
      start_at:
        type: string
      table_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: backend@example.com
    name: Equipo de Backend
  description: Servicio REST para la gestión de reservas multi-restaurante.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://ejemplo.com/terminos
  title: Restaurant Reservation API
  version: "1.0"
paths:
  /api/v1/holamundo:
    get:
      consumes:
      - application/json
      description: |-
        Este endpoint retorna un mensaje de saludo básico del sistema.
        Es útil para verificar que la API está funcionando correctamente.
        No requiere autenticación y siempre retorna un mensaje estático.
      produces:
      - application/json
      responses:
        "200":
          description: Saludo obtenido exitosamente
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Error interno del servidor
          schema:
            additionalProperties: true
            type: object
      summary: Obtener saludo básico del sistema
      tags:
      - HolaMundo
  /api/v1/holamundo/saludo:
    get:
      consumes:
      - application/json
      description: |-
        Este endpoint retorna un mensaje de saludo personalizado y más detallado.
        Incluye información adicional como timestamp y versión de la API.
        Ideal para pruebas más avanzadas del sistema.
      produces:
      - application/json
      responses:
        "200":
          description: Saludo personalizado obtenido exitosamente
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Error interno del servidor
          schema:
            additionalProperties: true
            type: object
      summary: Obtener saludo personalizado
      tags:
      - HolaMundo
  /holamundo/reserve:
    post:
      consumes:
      - application/json
      description: Este endpoint permite crear una nueva reserva para una mesa en
        un restaurante.
      parameters:
      - description: Datos de la reserva
        in: body
        name: reservation
        required: true
        schema:
          $ref: '#/definitions/request.Reservation'
      produces:
      - application/json
      responses:
        "201":
          description: Reserva creada exitosamente
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Solicitud inválida
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Error interno del servidor
          schema:
            additionalProperties: true
            type: object
      summary: Crea una nueva reserva
      tags:
      - Reservas
securityDefinitions:
  BearerAuth:
    description: Ingrese su token JWT con el prefijo **Bearer**
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
